export const GET_ALL_POKEMON = "GET_ALL_POKEMON";
export const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
export const GET_POKEMON_DETAIL = "GET_POKEMON_DETAIL";
export const CREATE_POKEMON = "CREATE_POKEMON";
export const GET_POKEMON_TYPES = "GET_POKEMON_TYPES";
export const CLEAR_SELECTED_POKEMON = "CLEAR_SELECTED_POKEMON";
